server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: spring-batch
  main:
    banner-mode: off
  jmx:
    enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:dbbatch
    driver-class-name: org.h2.Driver
    username: batch
    password: hctab

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    disable-ssl-validation: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic

scheduled:
  cron: 0 * * * * *